### Objective of the problem: The objective of this problem is to predict the Group number of each customer.

In [1]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"E:\Python basics\Pranjal Sir\9. Skillenza Hackethon\ABC_Bank_train_data.csv")

In [3]:
new = pd.read_csv(r"E:\Python basics\Pranjal Sir\9. Skillenza Hackethon\ABC_Bank_test_data.csv")


In [4]:
df.employment_st = df.employment_st.fillna('A73')
df.poi = df.poi.fillna(3)
df.age = df.age.fillna(35)
df.gurantors = df.gurantors.fillna('A101')
df.housing_type = df.housing_type.fillna('A152')

In [5]:
new.employment_st = new.employment_st.fillna('A73')
new.poi = new.poi.fillna(3)
new.age = new.age.fillna(35)
new.gurantors = new.gurantors.fillna('A101')
new.housing_type = new.housing_type.fillna('A152')

In [6]:
df.Group_no.value_counts()

2    353
3    254
1    193
Name: Group_no, dtype: int64

In [7]:
df1 = df.drop('serial number',axis=1)
new1 = new.drop('serial number',axis=1)

In [8]:
df_categorical = df1.select_dtypes('object').columns
new_categorical = new1.select_dtypes('object').columns

In [9]:
df.head()

serial number account_info  duration_month credit_history purpose  \
0              1          A11               6            A34     A43   
1              2          A12              48            A32     A43   
2              3          A14              12            A34     A46   
3              4          A11              42            A32     A42   
4              5          A11              24            A33     A40   

  savings_account employment_st  poi personal_status gurantors  ...  \
0             A65           A75  4.0             A93      A101  ...   
1             A61           A73  2.0             A92      A101  ...   
2             A61           A74  2.0             A93      A101  ...   
3             A61           A74  2.0             A93      A103  ...   
4             A61           A73  3.0             A93      A101  ...   

   property_type   age  installment_type housing_type credits_no  job_type  \
0           A121  67.0              A143         A152          2      A173   
1           A121  22.0              A143         A152          1      A173   
2           A121  49.0              A143         A152          1      A172   
3           A122  45.0              A143         A153          1      A173   
4           A124  53.0              A143         A153          2      A173   

  liables  telephone foreigner Group_no  
0       1       A192      A201        3  
1       1       A191      A201        1  
2       2       A191      A201        2  
3       2       A191      A201        1  
4       2       A191      A201        1  

[5 rows x 21 columns]

In [87]:
df1 = pd.get_dummies(df1, columns=df_categorical, drop_first=True)
new1 = pd.get_dummies(new1, columns=new_categorical, drop_first=True)


In [88]:
df1.shape

(800, 48)

In [89]:
new1.shape

(200, 47)

In [90]:
df1_x = df1.drop('Group_no',axis=1)
df1_y = df1['Group_no']

In [91]:
from sklearn.model_selection import train_test_split
train , test = train_test_split(df1,test_size=.2)
train_x = train.drop('Group_no', axis=1)
train_y = train['Group_no']
test_x = test.drop('Group_no', axis=1)
test_y = test['Group_no']


In [92]:
train_x = np.array(train_x)
train_y = np.array(train_y)
test_x  = np.array(test_x)
test_y  = np.array(test_y)

In [93]:
from keras.layers              import Dense, LSTM, Embedding
from tensorflow.keras.utils    import to_categorical
from keras.models              import Sequential
from keras.preprocessing.text  import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.optimizers import Adam

In [94]:
train_x = tf.keras.utils.normalize(train_x)
test_x  = tf.keras.utils.normalize(test_x)

In [95]:
from keras.layers import Conv2D , MaxPool2D , Flatten , Dense , Dropout

In [112]:
model = tf.keras.models.Sequential()                               # sequential mean fully connected

model.add(tf.keras.layers.Dense(256 , activation = tf.nn.relu))    # Hidden layers -- 128 neurons
model.add(tf.keras.layers.Dense(256 , activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(256 , activation = tf.nn.relu))

model.add(Dropout(0.2))
model.add(tf.keras.layers.Dense(4 , activation = tf.nn.softmax))  # Output Layer

adam = tf.keras.optimizers.Adam(learning_rate=0.001) # 0.001

In [113]:
model.compile(optimizer= adam , loss= 'sparse_categorical_crossentropy' , metrics= ['accuracy'] )

In [114]:
model.fit(train_x ,train_y  , epochs = 10 , batch_size = 128 , validation_split= .2)

Epoch 1/10
4/4 [==============================] - 2s 100ms/step - loss: 1.3278 - accuracy: 0.3945 - val_loss: 1.2185 - val_accuracy: 0.5156
Epoch 2/10
4/4 [==============================] - 0s 22ms/step - loss: 1.1940 - accuracy: 0.4297 - val_loss: 1.0824 - val_accuracy: 0.5156
Epoch 3/10
4/4 [==============================] - 0s 20ms/step - loss: 1.0922 - accuracy: 0.4297 - val_loss: 0.9989 - val_accuracy: 0.5156
Epoch 4/10
4/4 [==============================] - 0s 22ms/step - loss: 1.0173 - accuracy: 0.4434 - val_loss: 0.9585 - val_accuracy: 0.5234
Epoch 5/10
4/4 [==============================] - 0s 21ms/step - loss: 0.9617 - accuracy: 0.5273 - val_loss: 0.9351 - val_accuracy: 0.5469
Epoch 6/10
4/4 [==============================] - 0s 21ms/step - loss: 0.9236 - accuracy: 0.5508 - val_loss: 0.8953 - val_accuracy: 0.5469
Epoch 7/10
4/4 [==============================] - 0s 19ms/step - loss: 0.9091 - accuracy: 0.5488 - val_loss: 0.8782 - val_accuracy: 0.5234
Epoch 8/10
4/4 [==========

In [115]:
pred = model.predict(test_x)

5/5 [==============================] - 0s 3ms/step


In [103]:
pred_classes = np.argmax(pred , axis=1)  # max values index value
                                         # probability into classes

In [106]:
from sklearn.metrics import confusion_matrix
tab = confusion_matrix(pred_classes , test_y)
tab

array([[21, 11,  2],
       [14, 42, 23],
       [ 4, 14, 29]], dtype=int64)

In [107]:
tab.diagonal().sum() / tab.sum()

0.575

In [188]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import confusion_matrix,accuracy_score

model_names = []
acc = []

logreg = LogisticRegression(class_weight='balanced',max_iter= 2000)
dt = DecisionTreeClassifier(class_weight='balanced')
rf = RandomForestClassifier(class_weight='balanced',criterion='entropy',n_estimators=
                           250,max_depth=9)
knn = KNeighborsClassifier()
svc = SVC()
ada = AdaBoostClassifier(dt, n_estimators=250)

models = [logreg, dt,rf,knn,svc,ada]

for model in models:
    model.fit(df1_x, df1_y)
    pred = model.predict(new1)
    
    acc.append(accuracy_score(predicted, pred))
    
model_names = ['logreg', 'dt','rf','knn','svc','ada']
result = pd.DataFrame({'Accuracy':acc}, index=model_names)
result

ValueError: Classification metrics can't handle a mix of multiclass-multioutput and multiclass targets

In [165]:
pred

array([2, 3, 1, 3, 3, 1, 3, 3, 1, 2, 3, 3, 1, 1, 1, 1, 3, 2, 1, 3, 3, 3,
       1, 3, 2, 3, 1, 1, 1, 1, 2, 3, 1, 2, 3, 3, 3, 2, 1, 2, 2, 1, 3, 2,
       2, 1, 2, 3, 3, 3, 3, 1, 2, 3, 1, 3, 3, 2, 3, 2, 2, 3, 2, 2, 2, 2,
       3, 2, 1, 3, 1, 3, 2, 3, 2, 3, 1, 2, 2, 1, 1, 1, 2, 3, 2, 3, 1, 1,
       1, 2, 1, 3, 3, 1, 2, 1, 2, 3, 2, 2, 2, 2, 1, 3, 2, 2, 2, 1, 1, 3,
       2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 3, 3, 2, 3, 2, 1, 2, 3, 2, 3,
       3, 3, 3, 1, 3, 3, 1, 1, 1, 3, 2, 3, 2, 1, 2, 3, 2, 1, 3, 1, 2, 1,
       3, 2, 1, 3, 2, 2, 3, 1, 2, 2, 3, 2, 2, 2, 1, 2, 3, 1, 1, 1, 2, 3,
       3, 3, 2, 2, 1, 1, 1, 1, 1, 3, 1, 3, 1, 1, 2, 3, 2, 1, 3, 3, 1, 3,
       1, 1], dtype=int64)

In [30]:
score_dt = cross_val_score(rf,train_x,train_y, cv=5,scoring='accuracy')
score_dt

array([0.6328125, 0.640625 , 0.65625  , 0.671875 , 0.671875 ])

In [319]:
cor = []
col = df.columns
for i in col:
    cor.append(df['Group_no'].corr(df[i]))
cor

correl = pd.DataFrame({'col': col, 'corel':cor})
correl

col     corel
0       account_info  0.018239
1     duration_month -0.588725
2     credit_history  0.002485
3            purpose -0.031545
4    savings_account -0.016609
5      employment_st  0.003857
6                poi  0.259414
7    personal_status -0.014649
8          gurantors  0.029298
9     resident_since -0.026316
10     property_type -0.296965
11               age -0.003927
12  installment_type  0.030340
13      housing_type -0.098448
14        credits_no -0.056597
15          job_type -0.299299
16           liables -0.009469
17         telephone -0.255166
18         foreigner  0.111158
19          Group_no  1.000000

In [320]:
cols = list(correl.col[(correl.corel < -0.05) | (correl.corel > 0.05)])
cols

['duration_month',
 'poi',
 'property_type',
 'housing_type',
 'credits_no',
 'job_type',
 'telephone',
 'foreigner',
 'Group_no']

In [321]:
df.Group_no.value_counts()

2    353
3    254
1    193
Name: Group_no, dtype: int64

In [ ]:
lo

In [124]:
rf = RandomForestClassifier(class_weight='balanced',criterion='entropy',n_estimators=
                           250,max_depth=9)
rf.fit(train_x, train_y)
pred = rf.predict(test_x)

tab =  confusion_matrix(test_y, pred)
acc = accuracy_score(test_y, pred)
print("The Confusion Matrix\n ",   tab,        '\n------------')
print("The Accuracy Score is - ",  acc,        '\n------------')

The Confusion Matrix
  [[24 11  1]
 [ 7 44 19]
 [ 0 15 39]] 
------------
The Accuracy Score is -  0.66875 
------------


In [125]:
ada = AdaBoostClassifier(rf,n_estimators=150,learning_rate=0.05)
ada.fit(train_x, train_y)
pred = ada.predict(test_x)

tab =  confusion_matrix(test_y, pred)
acc = accuracy_score(test_y, pred)
print("The Confusion Matrix\n ",   tab,        '\n------------')
print("The Accuracy Score is - ",  acc,        '\n------------')


The Confusion Matrix
  [[24 12  0]
 [ 5 46 19]
 [ 0 16 38]] 
------------
The Accuracy Score is -  0.675 
------------


In [67]:
from sklearn.model_selection import GridSearchCV
search_dict = {"max_depth": range(3,10)
              }
grid = GridSearchCV(rf, param_grid = search_dict)
grid.fit(train_x , train_y)
grid.best_params_

{'max_depth': 7}

In [31]:
grid.best_score_

0.640625

In [34]:
feature_importance = pd.DataFrame()
feature_importance['columns'] = train_x.columns
feature_importance['Score'] = rf.feature_importances_
feature_importance.sort_values('Score', ascending=False).head(15)    


columns     Score
0        duration_month  0.253791
1                   poi  0.084145
3                   age  0.063452
44        job_type_A174  0.044318
4            credits_no  0.023943
42        job_type_A172  0.023774
45       telephone_A192  0.023345
37   property_type_A124  0.022423
2        resident_since  0.022319
43        job_type_A173  0.022009
13          purpose_A41  0.021784
31  personal_status_A93  0.019121
15          purpose_A42  0.018981
6      account_info_A12  0.018330
10   credit_history_A32  0.017331

In [41]:
df2 = df1.loc[:,['duration_month','poi','age','property_type_A124','job_type_A174','credits_no','Group_no','job_type_A172','telephone_A192','job_type_A173','resident_since']]

In [247]:
df2 = df.loc[:,['duration_month','poi','property_type','job_type','age','purpose','employment_st','Group_no']]

In [42]:
df2.head()

duration_month  poi   age  property_type_A124  job_type_A174  credits_no  \
0               6  4.0  67.0                   0              0           2   
1              48  2.0  22.0                   0              0           1   
2              12  2.0  49.0                   0              0           1   
3              42  2.0  45.0                   0              0           1   
4              24  3.0  53.0                   1              0           2   

   Group_no  job_type_A172  telephone_A192  job_type_A173  resident_since  
0         3              0               1              1               4  
1         1              0               0              1               2  
2         2              1               0              0               3  
3         1              0               0              1               4  
4         1              0               0              1               4

In [126]:
new = pd.read_csv(r"E:\Python basics\Pranjal Sir\9. Skillenza Hackethon\ABC_Bank_test_data.csv")
new.head()

serial number account_info  duration_month credit_history purpose  \
0              1          A14              24            A34     A46   
1              2          A12              18            A34     A43   
2              3          A11              20            A34     A42   
3              4          A14              12            A34     A43   
4              5          A12              12            A32     A40   

  savings_account employment_st  poi personal_status gurantors  \
0             A61           A75  4.0             A93      A101   
1             A61           A75  3.0             A92      A103   
2             A61           A75  1.0             A92      A101   
3             A65           A75  4.0             A93      A101   
4             A65           A71  1.0             A92      A101   

   resident_since property_type   age installment_type housing_type  \
0               4          A124  54.0             A143         A153   
1               4          A121  48.0             A141         A151   
2               4          A122  24.0             A143         A152   
3               4          A123  35.0             A143         A152   
4               2          A121  24.0             A143         A151   

   credits_no job_type  liables telephone foreigner  
0           2     A173        2      A191      A201  
1           2     A172        1      A192      A201  
2           2     A173        1      A191      A201  
3           2     A173        1      A191      A201  
4           1     A171        1      A191      A201

In [127]:
new.isnull().sum()

serial number       0
account_info        0
duration_month      0
credit_history      0
purpose             0
savings_account     0
employment_st       5
poi                 5
personal_status     0
gurantors           0
resident_since      0
property_type       0
age                 2
installment_type    0
housing_type        8
credits_no          0
job_type            0
liables             0
telephone           0
foreigner           0
dtype: int64

In [128]:
new.employment_st = new.employment_st.fillna('A73')
new.poi = new.poi.fillna(3)
new.age = new.age.fillna(35)
new.gurantors = new.gurantors.fillna('A101')
new.housing_type = new.housing_type.fillna('A152')

In [129]:
categorical = new.select_dtypes('object').columns
categorical

Index(['account_info', 'credit_history', 'purpose', 'savings_account',
       'employment_st', 'personal_status', 'gurantors', 'property_type',
       'installment_type', 'housing_type', 'job_type', 'telephone',
       'foreigner'],
      dtype='object')

In [130]:
new1 = pd.get_dummies(new, columns=categorical, drop_first=True)
new1.head()

serial number  duration_month  poi  resident_since   age  credits_no  \
0              1              24  4.0               4  54.0           2   
1              2              18  3.0               4  48.0           2   
2              3              20  1.0               4  24.0           2   
3              4              12  4.0               4  35.0           2   
4              5              12  1.0               2  24.0           1   

   liables  account_info_A12  account_info_A13  account_info_A14  ...  \
0        2                 0                 0                 1  ...   
1        1                 1                 0                 0  ...   
2        1                 0                 0                 0  ...   
3        1                 0                 0                 1  ...   
4        1                 1                 0                 0  ...   

   property_type_A124  installment_type_A142  installment_type_A143  \
0                   1                      0                      1   
1                   0                      0                      0   
2                   0                      0                      1   
3                   0                      0                      1   
4                   0                      0                      1   

   housing_type_A152  housing_type_A153  job_type_A172  job_type_A173  \
0                  0                  1              0              1   
1                  0                  0              1              0   
2                  1                  0              0              1   
3                  1                  0              0              1   
4                  0                  0              0              0   

   job_type_A174  telephone_A192  foreigner_A202  
0              0               0               0  
1              0               1               0  
2              0               0               0  
3              0               0               0  
4              0               0               0  

[5 rows x 48 columns]

In [131]:
new1 = new1.drop('serial number',axis=1)

In [49]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
new[new.select_dtypes(include = 'object').columns] = new[new.select_dtypes(include = 'object').columns].apply(le.fit_transform)

In [50]:
new.head()

serial number  account_info  duration_month  credit_history  purpose  \
0              1             3              24               4        7   
1              2             1              18               4        4   
2              3             0              20               4        3   
3              4             3              12               4        4   
4              5             1              12               2        0   

   savings_account  employment_st  poi  personal_status  gurantors  \
0                0              4  4.0                2          0   
1                0              4  3.0                1          2   
2                0              4  1.0                1          0   
3                4              4  4.0                2          0   
4                4              0  1.0                1          0   

   resident_since  property_type   age  installment_type  housing_type  \
0               4              3  54.0                 2             2   
1               4              0  48.0                 0             0   
2               4              1  24.0                 2             1   
3               4              2  35.0                 2             1   
4               2              0  24.0                 2             0   

   credits_no  job_type  liables  telephone  foreigner  
0           2         2        2          0          0  
1           2         1        1          1          0  
2           2         2        1          0          0  
3           2         2        1          0          0  
4           1         0        1          0          0

In [350]:
df1.columns

Index(['duration_month', 'poi', 'property_type', 'housing_type', 'credits_no',
       'job_type', 'telephone', 'foreigner', 'Group_no'],
      dtype='object')

In [351]:
new1 = new.loc[:,['duration_month','poi','age','property_type','job_type','credits_no','employment_st','housing_type','purpose']]

In [132]:
pred = ada.predict(new1)
pred

array([3, 2, 2, 3, 2, 1, 3, 3, 1, 2, 3, 3, 1, 1, 1, 1, 3, 2, 1, 3, 3, 3,
       2, 3, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 3, 3, 3, 3, 2, 3, 2, 1, 3, 2,
       2, 2, 2, 3, 2, 3, 2, 1, 3, 2, 1, 2, 3, 2, 3, 2, 2, 2, 2, 2, 2, 2,
       3, 2, 1, 3, 1, 3, 2, 3, 2, 3, 1, 2, 2, 1, 2, 1, 2, 3, 2, 3, 2, 1,
       1, 1, 1, 3, 3, 1, 2, 1, 2, 3, 2, 2, 1, 1, 1, 3, 2, 2, 2, 1, 3, 3,
       2, 2, 2, 3, 2, 1, 2, 1, 2, 2, 2, 1, 3, 1, 2, 3, 2, 1, 2, 3, 2, 3,
       2, 3, 3, 1, 3, 2, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 3, 2, 2, 1, 2, 2,
       3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 1, 2, 3, 2, 2, 1, 2, 3,
       2, 2, 3, 2, 1, 1, 2, 1, 2, 2, 1, 3, 2, 2, 2, 3, 2, 1, 3, 3, 1, 3,
       1, 1], dtype=int64)

In [168]:
pred.shape

(200,)

In [185]:
predicted = pd.DataFrame({'serial number':new['serial number'], 'group_no':pred})
predicted

serial number  group_no
0                1         2
1                2         3
2                3         1
3                4         3
4                5         3
..             ...       ...
195            196         3
196            197         1
197            198         3
198            199         1
199            200         1

[200 rows x 2 columns]

In [134]:
predicted.to_csv('ABC_Bank_submission.csv', index=False)